### ISSUE TITLE
Missing like-count for marble owner

### ISSUE THREAD

**Issue by bluewingtitan** [marblear/issues#33]
App Version: 2.4
Platforms: All (web-related)

To my knowledge there is no way for a normal user to find out how many likes a self-owned marble has gathered, since the editor always stays in edit mode (which does seem reasonable, but this number should be visible in there imho).

I feel like this probably is the most important number visible (or not visible in this case) to owners, since seeing this number going up basically is motivation-fuel to create more content + expected to be visible since this behavior is known from other social platforms by users.

**Comment by derwaldgeist** [comment]
Oh, yes, this unfortunately got lost when we redesigned the Marble editor. Before, there were actually 2 hearts. And we kicked the one out that showed the counter...

**Comment by derwaldgeist** [comment]
Fixed.
